-- Fill only missing character power levels. Existing values are preserved.
-- Baseline: the 185 populated rows in characters_rows (2).csv, with canon
-- strength used to place the remaining roster consistently within that scale.

begin;

with power_values(name, power_lvl) as (
 values
  ('Ada Wong', 58),
  ('Akaza', 82),
  ('Alastor Moody', 74),
  ('Albert Wesker', 82),
  ('Albus Dumbledore', 88),
  ('Aoi Todo', 77),
  ('Asta', 92),
  ('Atom Eve', 79),
  ('Baek Yoonho', 77),
  ('Baraka', 66),
  ('Battlebeast', 90),
  ('Bellatrix Lestrange', 69),
  ('Beru', 90),
  ('Biscuit Krueger', 81),
  ('Cha Hae-In', 81),
  ('Charlotte Roselei', 79),
  ('Choso', 73),
  ('Chris Redfield', 58),
  ('Chrollo Lucilfer', 84),
  ('Cole MacGrath', 88),
  ('Dante Zogratis', 91),
  ('Deidara', 77),
  ('Delsin Rowe', 86),
  ('Doma', 84),
  ('Draco Malfoy', 52),
  ('Ermac', 79),
  ('Ethan Winters', 68),
  ('Feitan Portor', 76),
  ('Fenrir Greyback', 66),
  ('Filius Flitwick', 68),
  ('Fuegoleon Vermillion', 84),
  ('Fujin', 87),
  ('Gaara', 80),
  ('Gellert Grindelwald', 87),
  ('Geras', 90),
  ('Ging Freecss', 88),
  ('Giyu Tomioka', 76),
  ('Go Gunhee', 79),
  ('Gon Freecss', 75),
  ('Goro', 78),
  ('Gyomei Himejima', 82),
  ('Gyutaro', 75),
  ('Hajime Kashimo', 87),
  ('Hantengu', 78),
  ('Harry Potter', 67),
  ('Hashirama Senju', 96),
  ('Hermione Granger', 66),
  ('Hinata Hyuga', 63),
  ('Hiromi Higuruma', 76),
  ('Hisoka Morow', 81),
  ('Homelander', 80),
  ('Horace Slughorn', 64),
  ('Igris', 80),
  ('Illumi Zoldyck', 79),
  ('Inosuke Hashibira', 65),
  ('Invincible', 84),
  ('Isaac Netero', 89),
  ('Itachi Uchiha', 89),
  ('Jack the Ripper', 81),
  ('Jill Valentine', 59),
  ('Jiraiya', 86),
  ('Jogo', 82),
  ('Johnny Cage', 68),
  ('Joseph Bertrand III', 84),
  ('Julius Novachrono', 96),
  ('Kabal', 75),
  ('Kakashi Hatake', 87),
  ('Kenjaku', 90),
  ('Kento Nanami', 71),
  ('Kessler', 90),
  ('Killua Zoldyck', 80),
  ('Kingsley Shacklebolt', 73),
  ('Kinji Hakari', 83),
  ('Kisame Hoshigaki', 82),
  ('Kitana', 74),
  ('Kite', 78),
  ('Kokushibo', 87),
  ('Kratos', 99),
  ('Kung Lao', 74),
  ('Kurapika', 79),
  ('Kyojuro Rengoku', 77),
  ('Langris Vaude', 80),
  ('Leon Kennedy', 57),
  ('Licht', 87),
  ('Liu Kang', 92),
  ('Lord Voldemort', 85),
  ('Lucius Malfoy', 61),
  ('Lucius Zogratis', 98),
  ('Luck Voltia', 74),
  ('Machi Komacine', 72),
  ('Madara Uchiha', 99),
  ('Magna Swing', 67),
  ('Mahito', 81),
  ('Maki Zenin', 82),
  ('Megumi Fushiguro', 78),
  ('Mei Mei', 72),
  ('Menthuthuyoupi', 86),
  ('Mereoleona Vermillion', 88),
  ('Meruem', 94),
  ('Might Guy', 95),
  ('Mileena', 69),
  ('Minato Namikaze', 94),
  ('Minerva McGonagall', 72),
  ('Mitsuri Kanroji', 74),
  ('Morel Mackernasey', 79),
  ('Mother Miranda', 86),
  ('Muichiro Tokito', 76),
  ('Muzan Kibutsuji', 89),
  ('Nacht Faust', 83),
  ('Naruto Uzumaki', 98),
  ('Neferpitou', 87),
  ('Neji Hyuga', 68),
  ('Nemesis', 78),
  ('Neville Longbottom', 57),
  ('Nezuko Kamado', 72),
  ('Nobara Kugisaki', 68),
  ('Noelle Silva', 86),
  ('Noob Saibot', 80),
  ('Nymphadora Tonks', 65),
  ('Obanai Iguro', 74),
  ('Obito Uchiha', 94),
  ('Omni-Man', 87),
  ('Orochimaru', 86),
  ('Pain', 90),
  ('Quan Chi', 85),
  ('Raiden', 95),
  ('Remus Lupin', 68),
  ('Rock Lee', 76),
  ('Rubeus Hagrid', 64),
  ('Ryomen Sukuna', 98),
  ('Sanemi Shinazugawa', 78),
  ('Sasuke Uchiha', 97),
  ('Satoru Gojo', 97),
  ('Scorpion', 80),
  ('Severus Snape', 76),
  ('Shaiapouf', 84),
  ('Shang Tsung', 86),
  ('Shao Kahn', 93),
  ('Shikamaru Nara', 66),
  ('Shinnok', 94),
  ('Shinobu Kocho', 70),
  ('Silva Zoldyck', 84),
  ('Sindel', 88),
  ('Sirius Black', 70),
  ('Soldier Boy', 78),
  ('Sub-Zero', 80),
  ('Sung Jinwoo', 100),
  ('Tanjiro Kamado', 75),
  ('Tengen Uzui', 75),
  ('The Beast', 95),
  ('Thomas Andre', 89),
  ('Thragg', 91),
  ('Toji Fushiguro', 83),
  ('Tsunade', 85),
  ('Uraume', 78),
  ('Uvogin', 80),
  ('Vanica Zogratis', 90),
  ('William Vangeance', 84),
  ('Yami Sukehiro', 89),
  ('Yoriichi Tsugikuni', 93),
  ('Yuji Itadori', 80),
  ('Yuki Tsukumo', 88),
  ('Yuno', 90),
  ('Yuta Okkotsu', 91),
  ('Zagred', 90),
  ('Zenitsu Agatsuma', 68),
  ('Zeno Zoldyck', 86),
  ('Zenon Zogratis', 90)
), updated as (
  update characters as c
  set "Power_lvl" = p.power_lvl
  from power_values as p
  where c.name = p.name
    and c."Power_lvl" is null
  returning c.name, c."Power_lvl"
)
select count(*) as characters_updated from updated;

commit;

-- Verification: this should return zero rows.
select name, universe, tier
from characters
where "Power_lvl" is null
order by universe, name;