-- Complete the major canonical relationship graph for the current roster.
-- Scope: recurring teammates, immediate family/partners, direct mentors, and major enemies.
-- Existing authored dialogue is preserved; new rows use an empty JSON array.

begin;

-- Remove rows that reference characters no longer present in the roster.
delete from public.rivalries r
where not exists (select 1 from public.characters c where c.name = r.a)
   or not exists (select 1 from public.characters c where c.name = r.b);

-- Insert the curated set directly. A later de-duplication keeps the oldest
-- row, preserving any existing authored dialogue over a new empty-lines row.
insert into public.rivalries (a, b, kind, lines)
values
  ('Asta','Yuno','teammates','[]'),
  ('Asta','Noelle Silva','teammates','[]'),
  ('Asta','Yami Sukehiro','mentor','[]'),
  ('Asta','Nacht Faust','mentor','[]'),
  ('Asta','Luck Voltia','teammates','[]'),
  ('Asta','Magna Swing','teammates','[]'),
  ('Asta','Dante Zogratis','enemies','[]'),
  ('Asta','Lucius Zogratis','enemies','[]'),
  ('Asta','Zagred','enemies','[]'),
  ('Yuno','William Vangeance','mentor','[]'),
  ('Yuno','Langris Vaude','teammates','[]'),
  ('Yuno','Zenon Zogratis','enemies','[]'),
  ('Yuno','Zagred','enemies','[]'),
  ('Yami Sukehiro','Charlotte Roselei','teammates','[]'),
  ('Yami Sukehiro','William Vangeance','teammates','[]'),
  ('Yami Sukehiro','Jack the Ripper','teammates','[]'),
  ('Yami Sukehiro','Dante Zogratis','enemies','[]'),
  ('Fuegoleon Vermillion','Mereoleona Vermillion','family','[]'),
  ('Noelle Silva','Vanica Zogratis','enemies','[]'),
  ('Julius Novachrono','Lucius Zogratis','enemies','[]'),
  ('Nacht Faust','Lucius Zogratis','enemies','[]'),
  ('Dante Zogratis','Vanica Zogratis','family','[]'),
  ('Dante Zogratis','Zenon Zogratis','family','[]'),
  ('Vanica Zogratis','Zenon Zogratis','family','[]'),
  ('Billy Butcher','Hughie Campbell','teammates','[]'),
  ('Billy Butcher','Frenchie','teammates','[]'),
  ('Billy Butcher','Kimiko Miyashiro','teammates','[]'),
  ('Billy Butcher','Homelander','enemies','[]'),
  ('Billy Butcher','Soldier Boy','teammates','[]'),
  ('Hughie Campbell','Starlight','family','[]'),
  ('Hughie Campbell','A-Train','enemies','[]'),
  ('Frenchie','Kimiko Miyashiro','family','[]'),
  ('Homelander','Queen Maeve','enemies','[]'),
  ('Homelander','Soldier Boy','enemies','[]'),
  ('Homelander','Stormfront','teammates','[]'),
  ('Homelander','Black Noir','teammates','[]'),
  ('Homelander','The Deep','teammates','[]'),
  ('Homelander','Sister Sage','teammates','[]'),
  ('Homelander','Stan Edgar','enemies','[]'),
  ('Homelander','Victoria Neuman','enemies','[]'),
  ('Starlight','The Deep','enemies','[]'),
  ('Starlight','Stormfront','enemies','[]'),
  ('Marie Moreau','Thomas Godolkin','enemies','[]'),
  ('Marie Moreau','Victoria Neuman','enemies','[]'),
  ('Captain Boomerang','The Flash','enemies','[]'),
  ('Captain Boomerang','Deadshot','teammates','[]'),
  ('Clayface','Batman','enemies','[]'),
  ('King Shark','Aquaman','enemies','[]'),
  ('King Shark','Harley Quinn','teammates','[]'),
  ('Metamorpho','Batman','teammates','[]'),
  ('Vibe','The Flash','teammates','[]'),
  ('Vibe','Cyborg','teammates','[]'),
  ('Wonder Woman','Superman','teammates','[]'),
  ('Supergirl','Superman','family','[]'),
  ('Hawkman','Mr. Terrific','teammates','[]'),
  ('Tanjiro Kamado','Nezuko Kamado','family','[]'),
  ('Tanjiro Kamado','Inosuke Hashibira','teammates','[]'),
  ('Tanjiro Kamado','Zenitsu Agatsuma','teammates','[]'),
  ('Tanjiro Kamado','Giyu Tomioka','mentor','[]'),
  ('Tanjiro Kamado','Tengen Uzui','teammates','[]'),
  ('Tanjiro Kamado','Hantengu','enemies','[]'),
  ('Nezuko Kamado','Zenitsu Agatsuma','family','[]'),
  ('Mitsuri Kanroji','Obanai Iguro','family','[]'),
  ('Gyomei Himejima','Sanemi Shinazugawa','teammates','[]'),
  ('Gyomei Himejima','Muichiro Tokito','teammates','[]'),
  ('Gyutaro','Tengen Uzui','enemies','[]'),
  ('Doma','Shinobu Kocho','enemies','[]'),
  ('Doma','Inosuke Hashibira','enemies','[]'),
  ('Kokushibo','Yoriichi Tsugikuni','family','[]'),
  ('Kokushibo','Muichiro Tokito','family','[]'),
  ('Kokushibo','Gyomei Himejima','enemies','[]'),
  ('Kokushibo','Sanemi Shinazugawa','enemies','[]'),
  ('Muzan Kibutsuji','Yoriichi Tsugikuni','enemies','[]'),
  ('Muzan Kibutsuji','Doma','mentor','[]'),
  ('Muzan Kibutsuji','Kokushibo','mentor','[]'),
  ('Muzan Kibutsuji','Gyutaro','mentor','[]'),
  ('Muzan Kibutsuji','Hantengu','mentor','[]'),
  ('Harry Potter','Draco Malfoy','enemies','[]'),
  ('Harry Potter','Rubeus Hagrid','family','[]'),
  ('Harry Potter','Sirius Black','family','[]'),
  ('Harry Potter','Remus Lupin','mentor','[]'),
  ('Harry Potter','Alastor Moody','mentor','[]'),
  ('Harry Potter','Neville Longbottom','teammates','[]'),
  ('Draco Malfoy','Lucius Malfoy','family','[]'),
  ('Draco Malfoy','Hermione Granger','enemies','[]'),
  ('Lucius Malfoy','Lord Voldemort','teammates','[]'),
  ('Bellatrix Lestrange','Lord Voldemort','teammates','[]'),
  ('Fenrir Greyback','Remus Lupin','enemies','[]'),
  ('Albus Dumbledore','Gellert Grindelwald','enemies','[]'),
  ('Albus Dumbledore','Filius Flitwick','teammates','[]'),
  ('Albus Dumbledore','Horace Slughorn','teammates','[]'),
  ('Albus Dumbledore','Rubeus Hagrid','mentor','[]'),
  ('Minerva McGonagall','Filius Flitwick','teammates','[]'),
  ('Minerva McGonagall','Horace Slughorn','teammates','[]'),
  ('Nymphadora Tonks','Remus Lupin','family','[]'),
  ('Nymphadora Tonks','Alastor Moody','mentor','[]'),
  ('Kingsley Shacklebolt','Alastor Moody','teammates','[]'),
  ('Neville Longbottom','Bellatrix Lestrange','enemies','[]'),
  ('Severus Snape','Horace Slughorn','mentor','[]'),
  ('Gon Freecss','Killua Zoldyck','teammates','[]'),
  ('Gon Freecss','Ging Freecss','family','[]'),
  ('Gon Freecss','Kite','mentor','[]'),
  ('Gon Freecss','Biscuit Krueger','mentor','[]'),
  ('Gon Freecss','Hisoka Morow','enemies','[]'),
  ('Gon Freecss','Neferpitou','enemies','[]'),
  ('Killua Zoldyck','Biscuit Krueger','mentor','[]'),
  ('Killua Zoldyck','Silva Zoldyck','family','[]'),
  ('Killua Zoldyck','Illumi Zoldyck','family','[]'),
  ('Killua Zoldyck','Zeno Zoldyck','family','[]'),
  ('Kurapika','Chrollo Lucilfer','enemies','[]'),
  ('Kurapika','Uvogin','enemies','[]'),
  ('Chrollo Lucilfer','Hisoka Morow','enemies','[]'),
  ('Chrollo Lucilfer','Feitan Portor','teammates','[]'),
  ('Chrollo Lucilfer','Machi Komacine','teammates','[]'),
  ('Chrollo Lucilfer','Uvogin','teammates','[]'),
  ('Isaac Netero','Meruem','enemies','[]'),
  ('Meruem','Neferpitou','teammates','[]'),
  ('Meruem','Shaiapouf','teammates','[]'),
  ('Meruem','Menthuthuyoupi','teammates','[]'),
  ('Kite','Neferpitou','enemies','[]'),
  ('Morel Mackernasey','Gon Freecss','mentor','[]'),
  ('Morel Mackernasey','Killua Zoldyck','mentor','[]'),
  ('Cole MacGrath','Zeke Dunbar','teammates','[]'),
  ('Cole MacGrath','Lucy Kuo','teammates','[]'),
  ('Cole MacGrath','Nix','teammates','[]'),
  ('Cole MacGrath','Kessler','enemies','[]'),
  ('Cole MacGrath','The Beast','enemies','[]'),
  ('Cole MacGrath','Joseph Bertrand III','enemies','[]'),
  ('Cole MacGrath','Sasha','enemies','[]'),
  ('Cole MacGrath','Bloody Mary','enemies','[]'),
  ('Cole MacGrath','The Devourer','enemies','[]'),
  ('Lucy Kuo','Nix','enemies','[]'),
  ('Delsin Rowe','Reggie Rowe','family','[]'),
  ('Delsin Rowe','Abigail Walker','teammates','[]'),
  ('Delsin Rowe','Eugene Sims','teammates','[]'),
  ('Delsin Rowe','Brooke Augustine','enemies','[]'),
  ('Abigail Walker','Brooke Augustine','enemies','[]'),
  ('Eugene Sims','Brooke Augustine','enemies','[]'),
  ('Invincible','Atom Eve','family','[]'),
  ('Invincible','Omni-Man','family','[]'),
  ('Invincible','Allen the Alien','teammates','[]'),
  ('Invincible','Bulletproof','teammates','[]'),
  ('Invincible','Cecil Stedman','mentor','[]'),
  ('Invincible','Angstrom Levy','enemies','[]'),
  ('Invincible','Conquest','enemies','[]'),
  ('Invincible','Anissa','enemies','[]'),
  ('Invincible','Thragg','enemies','[]'),
  ('Omni-Man','Cecil Stedman','enemies','[]'),
  ('Omni-Man','The Immortal','enemies','[]'),
  ('Omni-Man','Conquest','enemies','[]'),
  ('Omni-Man','Thragg','enemies','[]'),
  ('Thragg','Battlebeast','enemies','[]'),
  ('Robot','Monster Girl','family','[]'),
  ('Robot','Rex Splode','teammates','[]'),
  ('Robot','Bulletproof','teammates','[]'),
  ('Robot','The Immortal','teammates','[]'),
  ('Monster Girl','Rex Splode','teammates','[]'),
  ('Yuji Itadori','Aoi Todo','teammates','[]'),
  ('Yuji Itadori','Choso','family','[]'),
  ('Yuji Itadori','Kento Nanami','mentor','[]'),
  ('Yuji Itadori','Satoru Gojo','mentor','[]'),
  ('Yuji Itadori','Megumi Fushiguro','teammates','[]'),
  ('Yuji Itadori','Nobara Kugisaki','teammates','[]'),
  ('Yuji Itadori','Mahito','enemies','[]'),
  ('Yuji Itadori','Kenjaku','family','[]'),
  ('Satoru Gojo','Yuta Okkotsu','mentor','[]'),
  ('Satoru Gojo','Megumi Fushiguro','mentor','[]'),
  ('Satoru Gojo','Toji Fushiguro','enemies','[]'),
  ('Satoru Gojo','Ryomen Sukuna','enemies','[]'),
  ('Yuta Okkotsu','Maki Zenin','teammates','[]'),
  ('Yuta Okkotsu','Kinji Hakari','teammates','[]'),
  ('Yuta Okkotsu','Kenjaku','enemies','[]'),
  ('Maki Zenin','Nobara Kugisaki','teammates','[]'),
  ('Maki Zenin','Toji Fushiguro','family','[]'),
  ('Megumi Fushiguro','Toji Fushiguro','family','[]'),
  ('Megumi Fushiguro','Ryomen Sukuna','enemies','[]'),
  ('Kinji Hakari','Hajime Kashimo','enemies','[]'),
  ('Hajime Kashimo','Ryomen Sukuna','enemies','[]'),
  ('Hiromi Higuruma','Yuji Itadori','teammates','[]'),
  ('Jogo','Satoru Gojo','enemies','[]'),
  ('Jogo','Ryomen Sukuna','enemies','[]'),
  ('Mahito','Kento Nanami','enemies','[]'),
  ('Kenjaku','Yuki Tsukumo','enemies','[]'),
  ('Kenjaku','Choso','family','[]'),
  ('Uraume','Ryomen Sukuna','teammates','[]'),
  ('Mei Mei','Satoru Gojo','teammates','[]'),
  ('Electro','Spider-Man','enemies','[]'),
  ('The Scorpion','Spider-Man','enemies','[]'),
  ('Vulture','Spider-Man','enemies','[]'),
  ('Mantis','Star-Lord','teammates','[]'),
  ('Mantis','Drax the Destroyer','teammates','[]'),
  ('Nebula','Gamora','family','[]'),
  ('Yondu','Star-Lord','family','[]'),
  ('Yondu','Rocket Raccoon','teammates','[]'),
  ('Silver Surfer','Mr Fantastic','teammates','[]'),
  ('Liu Kang','Kung Lao','teammates','[]'),
  ('Liu Kang','Raiden','mentor','[]'),
  ('Liu Kang','Kitana','family','[]'),
  ('Liu Kang','Shang Tsung','enemies','[]'),
  ('Liu Kang','Shao Kahn','enemies','[]'),
  ('Liu Kang','Shinnok','enemies','[]'),
  ('Scorpion','Sub-Zero','enemies','[]'),
  ('Scorpion','Quan Chi','enemies','[]'),
  ('Scorpion','Noob Saibot','enemies','[]'),
  ('Sub-Zero','Noob Saibot','family','[]'),
  ('Kitana','Mileena','family','[]'),
  ('Kitana','Sindel','family','[]'),
  ('Kitana','Shao Kahn','enemies','[]'),
  ('Mileena','Shao Kahn','family','[]'),
  ('Mileena','Baraka','teammates','[]'),
  ('Sindel','Shao Kahn','family','[]'),
  ('Raiden','Fujin','family','[]'),
  ('Raiden','Shinnok','enemies','[]'),
  ('Raiden','Shang Tsung','enemies','[]'),
  ('Johnny Cage','Liu Kang','teammates','[]'),
  ('Johnny Cage','Goro','enemies','[]'),
  ('Kung Lao','Goro','enemies','[]'),
  ('Goro','Shao Kahn','teammates','[]'),
  ('Shang Tsung','Shao Kahn','teammates','[]'),
  ('Shang Tsung','Quan Chi','teammates','[]'),
  ('Shinnok','Quan Chi','teammates','[]'),
  ('Kabal','Sub-Zero','teammates','[]'),
  ('Ermac','Liu Kang','enemies','[]'),
  ('Geras','Liu Kang','teammates','[]'),
  ('Kratos','Shao Kahn','enemies','[]'),
  ('Naruto Uzumaki','Hinata Hyuga','family','[]'),
  ('Naruto Uzumaki','Minato Namikaze','family','[]'),
  ('Naruto Uzumaki','Jiraiya','mentor','[]'),
  ('Naruto Uzumaki','Gaara','teammates','[]'),
  ('Naruto Uzumaki','Sasuke Uchiha','family','[]'),
  ('Naruto Uzumaki','Pain','enemies','[]'),
  ('Naruto Uzumaki','Obito Uchiha','enemies','[]'),
  ('Sasuke Uchiha','Itachi Uchiha','family','[]'),
  ('Sasuke Uchiha','Orochimaru','mentor','[]'),
  ('Sasuke Uchiha','Deidara','enemies','[]'),
  ('Kakashi Hatake','Obito Uchiha','family','[]'),
  ('Kakashi Hatake','Might Guy','teammates','[]'),
  ('Kakashi Hatake','Minato Namikaze','mentor','[]'),
  ('Kakashi Hatake','Rock Lee','mentor','[]'),
  ('Might Guy','Rock Lee','mentor','[]'),
  ('Neji Hyuga','Hinata Hyuga','family','[]'),
  ('Hashirama Senju','Madara Uchiha','enemies','[]'),
  ('Madara Uchiha','Obito Uchiha','mentor','[]'),
  ('Obito Uchiha','Minato Namikaze','mentor','[]'),
  ('Kisame Hoshigaki','Itachi Uchiha','teammates','[]'),
  ('Tsunade','Jiraiya','teammates','[]'),
  ('Tsunade','Orochimaru','teammates','[]'),
  ('Jiraiya','Orochimaru','teammates','[]'),
  ('Chris Redfield','Claire Redfield','family','[]'),
  ('Chris Redfield','Jill Valentine','teammates','[]'),
  ('Chris Redfield','Albert Wesker','enemies','[]'),
  ('Chris Redfield','Leon Kennedy','teammates','[]'),
  ('Chris Redfield','Mother Miranda','enemies','[]'),
  ('Claire Redfield','Leon Kennedy','teammates','[]'),
  ('Claire Redfield','Mr. X','enemies','[]'),
  ('Leon Kennedy','Ada Wong','family','[]'),
  ('Leon Kennedy','Mr. X','enemies','[]'),
  ('Leon Kennedy','Albert Wesker','enemies','[]'),
  ('Jill Valentine','Carlos Oliveira','teammates','[]'),
  ('Jill Valentine','Nemesis','enemies','[]'),
  ('Jill Valentine','Albert Wesker','enemies','[]'),
  ('Albert Wesker','HUNK','teammates','[]'),
  ('Ethan Winters','Jack Baker','enemies','[]'),
  ('Ethan Winters','Mother Miranda','enemies','[]'),
  ('Ethan Winters','Lady Dimitrescu','enemies','[]'),
  ('Jack Baker','Joe Baker','family','[]'),
  ('Jack Baker','Mother Miranda','enemies','[]'),
  ('Lady Dimitrescu','Mother Miranda','teammates','[]'),
  ('Sung Jinwoo','Cha Hae-In','family','[]'),
  ('Sung Jinwoo','Go Gunhee','mentor','[]'),
  ('Sung Jinwoo','Baek Yoonho','teammates','[]'),
  ('Sung Jinwoo','Thomas Andre','teammates','[]'),
  ('Sung Jinwoo','Igris','family','[]'),
  ('Sung Jinwoo','Beru','family','[]'),
  ('Igris','Beru','teammates','[]')
on conflict (a, b) do nothing;

delete from public.rivalries newer
using public.rivalries older
where newer.id > older.id
  and least(newer.a, newer.b) = least(older.a, older.b)
  and greatest(newer.a, newer.b) = greatest(older.a, older.b);

commit;

-- Validation: these should both return zero rows.
select r.*
from public.rivalries r
where not exists (select 1 from public.characters c where c.name = r.a)
   or not exists (select 1 from public.characters c where c.name = r.b);

select c.name, c.universe
from public.characters c
where not exists (
  select 1 from public.rivalries r
  where r.a = c.name or r.b = c.name
)
order by c.universe, c.name;